### ISSUE TITLE
Linking Stylesheet and images from HTML

### ISSUE THREAD

**Issue by mp1pro** [allan-glasier/tea-cozy#1]
On opening the webpage, the stylesheet nor the images from the html loaded. This is due to the path being called like so
`/resources/css/style.css`
The path should be called like so; 
`./resources/css/style.css`
The dot before the path means the path is executed from the folder it is presently in. An alternative would be;
`resources/css/style.css` which would also work.

**Comment by allan-glasier** [comment]
strange against this was working for me when i was running a live server with VScode. Updated!
