### ISSUE TITLE
Linking Images from CSS

### ISSUE THREAD

**Issue by mp1pro** [allan-glasier/tea-cozy#2]
When linking resources from the css file, the path has to be relative to the css file. Right now, you have; 
`background-image: url('/resources/images/img-locations-background.jpg');`

We would have to use `../` to step out the CSS folder before stepping into the images folder like so;

`background-image: url('../images/img-mission-background.jpg');`

**Comment by allan-glasier** [comment]
strange this was working for me when i was running a live server with VScode. I have updated the links though so they are correct!
