### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [allan-glasier/tea-cozy#3]
### Criteria 1: HTML Structure  
* _Score Level:_ 4/4
* _Comment(s):_ the html setup was done very well
 
### Criteria 2: Visual Layout
* _Score Level:_ 3/4
* _Comment(s):_ The visual layout looks exactly like the mock-up. Only some of the images did not come through.
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 4/4
* _Comment(s):_ Flexbox styles were used appropriately.
 
### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 2/4
* _Comment(s):_ The implementation meets design and content specs given. However, the linking will need to be updated. 
 
### Overall Score: 13/16

**Comment by allan-glasier** [comment]
fixed the links!
